(define (mean ds)
  (exact->inexact (/ (apply + ds) (length ds))))
(define (square x) (* x x))
(define (std-dev ds u)
  (sqrt (/ (apply + (map (lambda (x) (square (- x u))) ds)) (length ds))))
(define (stats r)
  (let* ((ds (map time-second r))
         (u (mean ds))
         (s (std-dev ds u)))
    (list u s (apply min ds) (apply max ds))))

(define (benchmark n thunk)
  (map
   (lambda (i)
     (let ((start (current-time)))
       (thunk)
       (time-difference (current-time) start)))
   (iota n)))

(define (run-benchmark n thunk)
  (let* ((r (benchmark n thunk))
         (s (stats r)))
    (printf "~a\n" s)
    s))
